### PR TITLE
Front End TL;DR

### PR DESCRIPTION
**Pull request by sebdeckers**
What are everyone's thoughts on bringing FEDS TL;DR into SingaporeJS?
## Achievements over the past year
- [x] Host 1 meetup per month for 12 months without fail
- [x] Host events at different startups (13 companies at 12 offices have hosted so far)
- [x] Cover interesting front-end content (4–5 topics per session)
- [x] Reasonable attendance (~15–25 pax) for every session, from non-programmers to beginners to experts
- [ ] Get @timoxley to attend :weary: 
### Simple Interface

Have one person take charge of the event. Needs to coordinate with venue host, attendees, etc.

Typically this is via FB messenger and email. Sometimes phone, whatsapp, sms.
### Consistent Scheduling

Every 3rd Monday of the month. From 7:00pm to 10:00pm.
### Decentralised Location
- More people can attend as different events take place closer to their workplaces/homes.
- Added value of discovering new startups.
- Share venue/food burden over many hosts.
- Avoid repeat hosts indefinitely due to glut of startups.
### Single point of failure

So far this was mostly coordinated by myself (@cbas). If I'm unavailable it's not clear how to guarantee continuity.
### Audience Reach
- Facebook is decreasingly effective as they force publishers to buy ads.
- Any event I create is also only announced to the intersection of FEDS group members and my friends.
### Community Fragmentation

Competition between event formats is necessary for long-term success. However unite the JavaScript community and create a critical mass.
## Reasons to Merge

I think bringing the event under SingaporeJS has some benefits.
- Fixes single point of failure: If @cbas is unavailable, the event should continue. Should have a designated fallback, fixed rotation, or at least a place to call for help (i.e. this GitHub repo).
- Gain exposure to the SingaporeJS meetup. More people will find out about FEDS TL;DR.
- The SingaporeJS meetup page will better reflect the actual JavaScript activity in Singapore.

### CODE REVIEW

**Comment by notthetup** [comment]
Just to be clear.. it's still be 2 different events, but single organization umbrella?

**Comment by quannt** [comment]
:+1: for this

**Comment by sebdeckers** [comment]
@notthetup There are already several events under the SingaporeJS umbrella, I'm requesting a merge of Front End TL;DR.

**Comment by soareschen** [comment]
:+1: SGTM. Yup would be beneficial if we can gather all JS-related events in one place and get more organizers involved. i.e. Front End TL;DR, NodeBoats, NodeBots, NodeSchool, etc + more specialized meetups like Node.js.

On the other hand my concern is that some of these events are recurring quite frequently. Individual organizers might not have the capacity to get involved in planning multiple JS events in a month. I personally don't even attend Front End TL;DR because there are just too many monthly events happening in SG already.

So would be up to discussion what are the benefits we can provide with centralized organizer group. i.e. Have multiple working groups for different kinds of events? Better events scheduling so that they don't overlap in same week? etc.

**Comment by valentine** [comment]
:+1: bringing FEDS to the Meetup group will help with exposure, at least.

**Comment by soareschen** [comment]
Seems fine with everyone. Merging and welcome FEDS!

**Comment by sebdeckers** [comment]
:sparkles::heart::sparkles:

**Comment by notthetup** [comment]
:heart_eyes:

**Pull request merged**
